### ISSUE TITLE
feature request: sort columns, multi-tags for single cards, date

### ISSUE THREAD

**Issue by towingie** [kanriapp/kanri#224]
Thanks for project, started to use it everyday :)

- Would be great to make sort cards in columns by customizable priority parameter: (critical,high,low,etc)
- Also would be cool to can create some customizable tags and assign that tags (one or some) to single card (bug/feature/techdebt/etc)
- Aso to have Date parameter at card "Due", which will highlight it (by colored border or some other way) when we arrive to that date
- Also make possible to create linked (or single) card for multiple boards.. 
- Maybe make Card description markdown-aware :)

tasks:
- Make task in cards editable
- make them movable in list of tasks
- show unchecked/checked(todo/done) tasks in card view (at dashboard)

**Comment by trobonox** [comment]
Thanks a lot for your suggestions! These are some pretty good ideas and I will definitely consider implementing them. Especially card tasks are something I want to improve and your ideas perfectly correspond with what I had in mind for them.

Sadly I have been busy with personal matters lately, but I will add all of these to the roadmap (you can view it right here in the projects tab on GitHub) and work on some of these as soon as I have more time. 

If there's anything else you need help with or you find a bug, feel free to open another issue.

**Comment by trobonox** [comment]
Just as an update, following features have all been implemented:
- Card tags
- Due date
- Rich text for card descriptions (not exactly markdown but the syntax is similar)
- Editable and moveable tasks and a display of their completion status on each card itself

The other ideas you have are good but are definitely not a current priority.

**Comment by trobonox** [comment]
Closing this issue because most of the features here have been implemented. If you believe any is missing and you would still like to have them added, please open individual issues for each feature so I can track them better.
