### ISSUE TITLE
Inconsistency for import/export board

### ISSUE THREAD

**Issue by PeterP2** [kanriapp/kanri#313]
Export board is found at the top right (three dots)
but import board is found under Import/Export menu on the left side and there in the section 'partial import'

**Comment by trobonox** [comment]
Thanks for pointing this out.
For consistency reasons I could also add something like a dropdown menu to export one single board from the import/export menu.

**Comment by PeterP2** [comment]
Yes that would be very helpful.
I think the import/export menu should include all possible imports/exports
- full export
- boards (not yet included)
- themes (not yet included)
- maybe more in future (e.g. 'settings')

Nevertheless within the sub-windows the partial import/export is very helpful too.
- within settings menu (maybe there will be other/more setting-files in the future, just 'themes' at the moment)
- within board

Maybe worth thinking about ability of adding date/time to the filename like
kanri_theme_export 20230910-0920 .json
kanri_data_export 20230910-1711.json
(reverse date 'yyyymmdd' is common for correct sorting in file list)

**Comment by trobonox** [comment]
I have added a dropdown for individual boards in the import/export menu. I will probably revisit settings and import/export pages at a later point, so this is the only fix I will add for now.
