### ISSUE TITLE
Card Cursor Image Position Incorrectly Calibrated With Scroll Position

### ISSUE THREAD

**Issue by immijimmi** [kanriapp/kanri#446]
![kanri_x1mFQ7OVep](https://github.com/trobonox/kanri/assets/9651027/3d719adf-f44b-40a1-8d7d-bc24efe16a6a)

It seems that the offset being applied to the cursor image when a card is dragged is causing it to be rendered a little too far to the right when the scrollbar is all the way to the left, and when scrolling to the right the render position quickly becomes too far to the left. When scrolled far enough to the right, the cursor image is rendered so far to the left that it's not initially visible until the cursor is moved to the right.

The card is correctly dropped at the cursor's location when left mouse is released, and other cards move out of the way based on the cursor's location and not the hovering card's location.

**Comment by trobonox** [comment]
I have investigated this issue and have fixed the incorrect offset for both columns and cards. The fix will be out with the next release.

**Comment by trobonox** [comment]
I am sorry that it took so long, it's one of the issues I wasn't able to get fixed for the longest time. The new behaviour is now out with the latest release v0.8, where this issue is finally solved!
