### ISSUE TITLE
‌‌Can it be supported without Tarui?

### ISSUE THREAD

**Issue by kankanai** [kanriapp/kanri#530]
‌‌‌I want to run without using TarUI and publish it as an HTML website. I don't know if it's possible, thank you for your open source

**Comment by sjustintaylor** [comment]
Probably not, at least not without rebuilding the way the app handles persistent data storage to use some form of WebStorage. Currently it's using [tauri-plugin-store](https://github.com/tauri-apps/tauri-plugin-store) to persist data. This isn't going to work in a browser.

**Comment by kankanai** [comment]
> Probably not, at least not without rebuilding the way the app handles persistent data storage to use some form of WebStorage. Currently it's using [tauri-plugin-store](https://github.com/tauri-apps/tauri-plugin-store) to persist data. That plugin isn't going to work in a browser.
> 
> If you refactor that out, it most likely wouldn't take much to host the app on Cloudflare pages

‌Sure, here's the translation of the text you provided:Yes, I hope it can become a web application with a desktop version that can be embedded directly with a URL. Or, have you considered using Electron or SQLite?
