### ISSUE TITLE
Ability to change description text input field size

### ISSUE THREAD

**Issue by Rostezkiy** [kanriapp/kanri#585]
I think it would be nice if i could stretch description text field. Sometimes text is too large and hard to edit inside small window.
<img width="504" alt="2024-06-20_15-59" src="https://github.com/trobonox/kanri/assets/73363254/2c7046f3-8474-4c04-bae8-a3a2f812c0e0">

Example:

https://github.com/trobonox/kanri/assets/73363254/1f9db62d-589e-4059-8b14-b8e91dc38847

Kanri 0.7.0
Windows 10, 64bit

**Comment by trobonox** [comment]
Thanks for your suggestion, I will see if it is possible for me to add this (the description is not a standard textarea input but handled by TipTap to allow rich text inside)

**Comment by trobonox** [comment]
Implemented this, will be out with the next release

**Comment by trobonox** [comment]
Out with the latest release
