### ISSUE TITLE
Pressing Enter In Settings should restricted

### ISSUE THREAD

**Issue by mshami85** [kanriapp/kanri#595]
**Describe the bug**
In settings page, windows latest version ... press enter > this will causes delete data without confirmation

**To Reproduce**
1. Go to 'settings'
2. press  'ENTER KEY'

3. Every thing will be deleted ... with information message box

**Expected behavior**
nothing must be affected without focusing first,
delete confirmation message must be

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [v0.7.1]

**Comment by trobonox** [comment]
Thanks for reporting this issue, I will look into it and see if I can do anything to prevent this behavior.

**Comment by trobonox** [comment]
Apologies for the delayed response, this was a bug in the way I implemented the confirmation popup and should be fixed now.
This fix will be out with the next release.

**Comment by trobonox** [comment]
The latest release is finally out, this is fixed with v0.8.
