### ISSUE TITLE
Clear the search textbox with a button

### ISSUE THREAD

**Issue by jershon** [kanriapp/kanri#602]
To clear the _search textbox_, I can either press the return key multiple times or select the text and press the return key. It is a little time consuming, and sometime I prefer to look for the desired card by myself so I don't have to clear the _search textbox_ after.

A solution would be to add a little "clear" button that removes the text in the textbox. Something like in this picture:

![search_textbox](https://github.com/trobonox/kanri/assets/33510663/f53da57e-edc6-4113-b8e4-f17e4a054fb6)

Clicking the little cross would clear the _search textbox_.

**Comment by trobonox** [comment]
Thanks for pointing this out, I just added this feature and it will be out with the next release.

**Comment by trobonox** [comment]
Apologies for the long wait, this is finally out with Kanri v0.8 so make sure to get the latest version.

**Comment by jershon** [comment]
It's working great. Thank you <3
