### ISSUE TITLE
Tag text colour is always white in card view

### ISSUE THREAD

**Issue by Meeshoo** [kanriapp/kanri#604]
**Describe the bug**
When you click into a card with tags, the text on the tags is always white. This makes these hard to read in some situations. I imagine the text colour should be selected based on the tag colour as it does in the main view.

This is also the case for the tag selection dropdown when adding a tag to a card.

**To Reproduce**
1. Open a card
2. Add a tag
3. Change tag colour in "Edit Tags" menu
4. Click back into card

**Expected behavior**
The tag text colour is set based on the tag colour so it is readable, same as in the main view.

**Screenshots**
![Screenshot from 2024-07-13 10-26-05](https://github.com/user-attachments/assets/bc74abdd-a5e3-454e-928b-ddfa63a750d8)
![Screenshot from 2024-07-13 10-38-02](https://github.com/user-attachments/assets/14f91969-205f-4541-b87f-4139438bcf87)

**Desktop:**
 - OS: Fedora 40
 - Browser: N/A
 - Version: v0.7.1

**Comment by trobonox** [comment]
Thanks for raising awareness about this issue. 
Unfortunately, as opposed to the display on the main view the tag input is controlled by an external library (and I have less control over it). I will have to see to what extent it's possible to fix the contrast issue, but hopefully it's somewhat doable.
Will let you know if there's any updates on the matter.

**Comment by trobonox** [comment]
Added a fix. To have this apply to current tags (once the feature is out with the next release), you will need to set the global tag color again once. All new tags will have better contrast by default.

<img width="331" alt="image" src="https://github.com/user-attachments/assets/3d2502d0-1d7e-4b28-8937-de012dcdb687">

**Comment by trobonox** [comment]
Apologies for the long wait, this is now out with Kanri v0.8, so make sure to update :)
