### ISSUE TITLE
Due data countdown should round days up

### ISSUE THREAD

**Issue by pedroexenberger** [kanriapp/kanri#614]
**Describe the bug**
Not sure if a bug as it may depend on interpretation. But:
[The countdown due date rounds days down](https://github.com/trobonox/kanri/blob/a118b55c6e37c135c05759d4875d07f7258d6f94/components/kanban/Card.vue#L315). For example, say that on Friday afternoon you set you set a due date to Monday morning. The card will say that the card is due in two days.  I think this is misleading considering the typical way humans think at day intervals.  Although it will take 2 and a half days to happen, humans count days in absolute terms. Monday is roughly 3 days from Friday. Two days from Friday would be Sunday.

**To Reproduce**
1. Create a card.
2. Add a due date.
3. Set the countdown due date option.

**Expected behavior**

When a due date is more than one day, the countdown should count all days covered by the timespan.

**Comment by trobonox** [comment]
Thanks for letting me know about this issue. 

The current algorithm does indeed round down and to me it made sense in the moment, but it's probably better to round up as you suggested.
At the moment I am unable to do any development but once I can pick it up again I will take a look and see if I can change this behavior.

**Comment by pedroexenberger** [comment]
Great, thanks!

**Comment by trobonox** [comment]
Good news, it's done! Instead of rounding everything down I'm now rounding up and it seems to be working fine.
Not closing this issue yet until the feature is actually out (will be with the next release; might take a while since there's a lot of WIP stuff preventing me from releasing the current code as-is).

**Comment by trobonox** [comment]
Sorry for the long wait, this is now released with Kanri v0.8!
