### ISSUE TITLE
`⌘CMD` + `B` for bold text conflicts with shortcut to add new column

### ISSUE THREAD

**Issue by badlydrawnrob** [kanriapp/kanri#623]
A regularly used command (`cmd + b`) when the view has the card open "breaks" the board by adding an empty column. I'd advise changing the keyboard shortcut, or disabling it when in card view.

https://github.com/user-attachments/assets/25a34217-76c1-49db-9444-2c44726da4b3

**Comment by trobonox** [comment]
Good catch! I should probably just disable all keyboard shortcuts when in card view.

**Comment by trobonox** [comment]
Fixed, will be out with the next release.

**Comment by trobonox** [comment]
Fix is now released with Kanri v0.8.

**Comment by badlydrawnrob** [comment]
@trobonox All good, I haven't been using the app religiously but downloaded the latest version — good work! I'd probably use it more if I were working in a team, but I'll have to build the habit 😛
