### ISSUE TITLE
`ol` list is broken

### ISSUE THREAD

**Issue by badlydrawnrob** [kanriapp/kanri#624]
A numbered `ol` breaks formatting in card view.

https://github.com/user-attachments/assets/91aa9145-49bd-411a-9dcc-58445ef418df

**FYI** I'm on an Intel MacOS Monterey latest version.

**Comment by trobonox** [comment]
That's interesting. Seems like some kind of styling bug. 
(I probably forgot to apply the Kanri-specific theme styling to the `ol` elements inside the editor which is provided by the TipTap library).

**Comment by trobonox** [comment]
<img width="621" alt="image" src="https://github.com/user-attachments/assets/23408d2b-91ee-4473-87ee-fed81ced4c7e">

Fixed! Seems like it was indeed some missing styling.
Will be out with the next release (similar to what you suggested in one of the other issues, I tend to batch smaller fixes together into bigger releases).

**Comment by trobonox** [comment]
Fix is out with Kanri v0.8.
