### ISSUE TITLE
Inline code doesn't clear formatting very easily (if you need to edit text)

### ISSUE THREAD

**Issue by badlydrawnrob** [kanriapp/kanri#625]
Inline `code` with backticks is a little hard to get rid of. I guess you've got a few basic options here, as I'm not sure how this would be solved programatically. Either you add buttons like a WSIWYG editor to clear formatting, or you replicate what Github does with a `write`/`preview` mode .. or ... something else!

https://github.com/user-attachments/assets/1ec24a34-5be2-4c9b-9db3-3a1c6cd15a6b

There's a workaround like I've shown in the screencast. I tend to use backticks a lot, so it might be a minor problem for others.

**Comment by badlydrawnrob** [comment]
Oh. TipTap seems very capable however you decide to use it. I think you mentioned you use Nuxt for the other stuff — I have a friend who works there! I'm sure there's lots of stuff simpler than working with [Elm Lang](https://elm-lang.org/) (the packages for sure are more extensive) but javascript's syntax, it's speed of change and unwieldy nature put me off. I only need it for small things anyway.

Is Nuxt easy to use? I'm not in the business of creating large apps, but I haven't seen a small (but sizeable) example of Nuxt out in the wild that I could understand, or a good introduction book. It's quite different conceptually to Elm Lang.

**Comment by badlydrawnrob** [comment]
FYI: [Bear App](https://bear.app/) manages the state of the text formatting very nicely (I'm pressing `spacebar` and `delete` and alternating between those at the start of the video)


https://github.com/user-attachments/assets/3a919d0f-a0c0-4e01-bf39-c499fc393a34

**Comment by trobonox** [comment]
> Oh. TipTap seems very capable however you decide to use it. 

Absolutely, it's mostly a matter of configuration so I just need to figure out the best way to do that. 

> I think you mentioned you use Nuxt for the other stuff — I have a friend who works there! 

Yup, I use Nuxt to build the main parts of the app. Also very cool, the people in the Nuxt team are really nice and very talented people.

> I'm sure there's lots of stuff simpler than working with [Elm Lang](https://elm-lang.org/) (the packages for sure are more extensive) but javascript's syntax, it's speed of change and unwieldy nature put me off. I only need it for small things anyway.

Never used Elm so I can't compare anything here, but generally JavaScript is great for development speed. Once you've found some tools you like (in my case Vue/Nuxt) it's great for building out things quickly. The ecosystem overall definitely has some issues but I'm fairly happy with it overall.

> Is Nuxt easy to use? I'm not in the business of creating large apps, but I haven't seen a small (but sizeable) example of Nuxt out in the wild that I could understand, or a good introduction book. It's quite different conceptually to Elm Lang.

Yes, Nuxt is pretty easy to use! In Kanri I'm not even using a lot of Nuxt-specific features but the ecosystem is great and it adds a lot of nice things on top of Vue.js. I think when it comes to examples you can take a look at some repos made by Atinux (one of the original creators of Nuxt) or if you're into video courses Vue School has some Nuxt courses which seem to be quite comprehensive (Mastering Nuxt is the main one I believe).

**Comment by trobonox** [comment]
![Image](https://github.com/user-attachments/assets/7f609eef-8e0b-4b6d-a194-82babb880cb1)

Update: I've added a little floating menu when you select text which should allow easily toggling the formatting. 

I've looked into just fixing the weird behaviour and making it more intuitive directly inside the editor but it seems like that needs a little more tweaking of the TipTap behaviour (a part of it is available with a plugin but it only applies to ul/ol lists and nothing else unfortunately).

**Comment by badlydrawnrob** [comment]
@trobonox All sounds good so far 👍

**Comment by trobonox** [comment]
Update: Kanri v0.8 is out with the new floating menu.
Some extra remarks: to get rid of bullet points, you can "outdent" them using Shift + Tab, to get rid of code blocks you can enter a new line without formatting using Shift + Enter. It seems like the TipTap editor mostly tries to mimic the editing experience of software like Word/Google Docs etc., but it's not always that intuitive.

**Comment by trobonox** [comment]
I might come back to this at a later point, but for now I'd say the issue is somewhat solved. If you're not of the same opinion, feel free to reopen the issue with some extra suggestions on how the editing experience could be further improved. (But keep in mind that TipTap is not that easy to configure so the issue might stay open for a long time then haha)
