### ISSUE TITLE
RPM Package for openSUSE/Fedora users

### ISSUE THREAD

**Issue by JGMelon22** [kanriapp/kanri#649]
**Is your feature request related to a problem? Please describe.**
Hi, first of all, congrats for the project, it really helps my daily basis of studies and codding sessions. Is it possible to create an .rpm package for Kanri? It would really be great for openSUSE an Fedora users :)  

**Describe the solution you'd like**
There is a small but reliable project called [dpm](https://github.com/kanriapp/kanri/issues), which looks like a "spiritual successor" to Alien, and is really handy dandy helping this kinda of conversions (deb to rpm)

**Comment by trobonox** [comment]
Thanks for your suggestion. This is something I certainly want to support, but it has some caveats.

It seems that as of recently, Tauri also supports .rpm builds. I recently noticed this when building Kanri on my machine (I run Fedora). The only issue is that I'm not sure whether I can replicate this behaviour when creating release builds which use Ubuntu GitHub Actions runners.

I'll have to test it out once I'm nearing the next release. Will keep you updated if there's any progress on this matter.

**Comment by trobonox** [comment]
Good news: The latest app release has an rpm build available! From my testing in development the rpm builds worked fine, but I have changed some internal things with package dependencies for Linux, so please let me know if it works for you :) 
You can find the download in the releases or on the official website.

If everything works fine, feel free to close this issue.
