### ISSUE TITLE
How to set card background color?

### ISSUE THREAD

**Issue by sweetman-zz** [kanriapp/kanri#701]
Hello all,
It's not quite a request, but it could be (!).
I'm using Kanri 0.8 on windows 10, but I can't find a way to set the card background color as seen on kanriapp.com.
Am I missing something?
TIA
tony

**Comment by trobonox** [comment]
Hi, you can find the feature to change the color of a card when you click on the card (left-click). It will open following menu, where the option to change the card color is located next to the card's name (the little circle):
<img width="621" alt="Screenshot 2024-10-29 at 18 49 52" src="https://github.com/user-attachments/assets/aa7932ed-d942-42a1-96f9-be378c4c845c">
Hope that helps! If not, please feel free to ask more clarifying questions.

**Comment by sweetman-zz** [comment]
Perfect! thank you! 
I never could have found it without your help.
Tony

**Comment by trobonox** [comment]
Do you think it is a little too small or is the placement itself hard to find? 
I'm closing the issue because your problem is solved, but I'd like to understand why you were struggling to find it so I can improve the app's design.

**Comment by sweetman-zz** [comment]
It's a bit hidden. I searched everywhere in the docs, blog, website. I was able to know you can set the card color from the sample images on website, but didn't figured out where to set the card color until you pointed me in the right direction.
I would expect to see the color selector in another position: see attachment.
Tony

Attachment:
![card color](https://github.com/user-attachments/assets/16ae9ca6-6f72-4642-abb7-b0555465e7f1)

**Comment by trobonox** [comment]
Thanks for your insights! I will change the position in a more obvious place when I have some time.
Moreover, you have a good point with the docs. It might be a worthwhile investment to write a small "getting started" guide which explains the basic features of boards and cards.
