### ISSUE TITLE
Linux data file location

### ISSUE THREAD

**Issue by lordofscripts** [kanriapp/kanri#717]
On a Linux system, what is the location of the user's data file & configuration? I couldn't find `~/.kanri*` nor `~/.config/kanri*`

I know there is an Export function, but when I _selectively_ backup my system, I would like to know which directory to include.

**Comment by trobonox** [comment]
You can find the storage location here: https://www.kanriapp.com/getting-started/faq/#where-is-my-data-saved-can-i-change-the-location

Both boards and configuration are stored in the .kanri.dat file.
