### ISSUE TITLE
Zoom buttons swapped

### ISSUE THREAD

**Issue by leherkom** [kanriapp/kanri#723]
**Describe the bug**
When setting the zoom, the button to increase the zoom is on the left and the one to decrease is on the right. I feel like this should be the other way round, like most other controls.

**To Reproduce**
Set zoom level anywhere, e.g. in a board or the settings.

**Expected behavior**
The button for decreasing the zoom level should be to the left of the control, and the one for increasing should be on the right.

**Screenshots**
![Screenshot_20241117_112021](https://github.com/user-attachments/assets/692ce4bc-f548-449f-8855-bb737b74fbc3)

**Desktop (please complete the following information):**
 - OS: Linux AppImage, Version 0.8.0_amd64

**Comment by leherkom** [comment]
I'm willing to fix this if the issue is accepted, feel free to assign me if you do.

**Comment by trobonox** [comment]
Thanks for your report! This is a small oversight and feel free to contribute a fix. I will assign you this issue.
