### ISSUE TITLE
Linter does not run

### ISSUE THREAD

**Issue by leherkom** [kanriapp/kanri#726]
**Describe the bug**
When running `yarn lint` locally, it will throw an error and die.

**To Reproduce**
Locally installed environment after installing latest NodeJS LTS and running `yarn install`.

1. `cd` into repository root
2. Run `yarn lint`

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm
 - Version: Branch `main`

**Additional context**
Node Version: v22.11.0 LTS
Yarn Version: 1.22.22

Error message:

❯ yarn lint
yarn run v1.22.22
$ eslint "**/*.{js,ts,vue}"

Oops! Something went wrong! :(

ESLint: 9.15.0

Error: ESLintFlatConfigUtils: Different instances of plugin "@typescript-eslint" found in multiple configs: nuxt/typescript/setup, typescript-eslint/base. It's likely you misconfigured the merge of these configs.

**Comment by trobonox** [comment]
Thanks for reporting this! As the error indicates, it's probably a misconfiguration on my end (I recently revised the config together with another contributor, but we probably accidentally added something twice).
I've tweaked the config a little and at least on my machine, it seems to work now (pushing the commit in a bit).

**Comment by trobonox** [comment]
Pushed the commit, can you check if it works now?

**Comment by leherkom** [comment]
I'm getting a different error now, I'll paste it below:

```bash
❯ yarn lint
yarn run v1.22.22
$ eslint "**/*.{js,ts,vue}"

Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting (...)/Repos/kanri/components/CustomThemeEditor.vue
```

**Comment by trobonox** [comment]
Re-installed dependencies and I'm getting the same error now... Need to look into this a bit more but I remember struggling with the new ESLint flat config format and making things work correctly.

**Comment by leherkom** [comment]
Haha yeah, I've been there. Thanks for looking into it!

**Comment by trobonox** [comment]
Seems like there's some bug in `typescript-eslint` which causes this issue. Not sure if I can fix it at the moment, I might need to wait a few days until the fix is inside the `@nuxt/eslint` module.

**Comment by trobonox** [comment]
Seems like downgrading ESLint to 9.14.0 works, at least on my machine. Pushing the commit in a bit so you can try it out.

**Comment by leherkom** [comment]
Yep, that does it. The linter now complains in two places (Modal.vue and import.vue) when I run it on `main` but it does lint and the process doesn't die early anymore.

**Comment by trobonox** [comment]
Great! Don't worry about those two issues, one is related to regex and I'm not quite sure why it complains about it and the other is a fundamental flaw in my Modal implementation which can't be fixed without a pretty significant rewrite.
If everything else is good feel free to close thhe issue.

**Comment by leherkom** [comment]
The linter seems to complain about the escape of the slash character in that regex because it's placed inside a character class - so there can't be a limiter anyways until the character class is closed with a ]. A quick test in regex101.com agrees with that.

I wanted to test if removing it breaks anything but unfortunately the app doesn't start for me anymore:

```bash
❯ yarn tauri dev
yarn run v1.22.22
$ (...)/Repos/kanri/node_modules/.bin/tauri dev
     Running BeforeDevCommand (`yarn dev`)
$ nuxt dev
Nuxt 3.14.159 with Nitro 2.10.4                                                               5:22:56 PM
                                                                                              5:22:56 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose


[5:22:57 PM]  ERROR  Cannot start nuxt:  require() of ES Module (...)/Repos/kanri/node_modules/string-width/index.js from (...)/Repos/kanri/node_modules/wide-align/align.js not supported.
Instead change the require of index.js in (...)/Repos/kanri/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.

  Instead change the require of index.js in node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
  at TracingChannel.traceSync (node:diagnostics_channel:315:14)
  at Object.<anonymous> (node_modules/wide-align/align.js:2:19)
```

That seems unrelated to this one however, I'll close this issue.

**Comment by trobonox** [comment]
Very strange, this seems like some kind of dependency problem again and those are quite difficult to figure out because in most cases I'm unable to reproduce them.

**Comment by trobonox** [comment]
Update: after more people reported the same issue I have bumped some package versions and refreshed the lockfiles. The issues seem to be gone now.
