### ISSUE TITLE
[FR] Card background color inherit from tag

### ISSUE THREAD

**Issue by KronosTheLate** [kanriapp/kanri#727]
I can set the color for tags, which is awesome. It would be really nice if I could have that color inherited by any card with that tag. 

If adding this, it would also be nice to set column colors, and be able to select "inherit color from column" by default. This might require a "refresh colors" button for cards that have moved columns. Or, the color is updated automatically when the card is moved (when the color is set to be inherited from the column.

In the case of mixed tags, I guess an option would be to do a weighted average. But the main use-case for me is adding a single tag that I use to indicate the project.

**Comment by trobonox** [comment]
Thanks for your suggestion. I'm not sure if that's not a little too many color features and it might be a little too much color overlap. Moreover, it might be hard to integrate these features in a way that is obvious enough that people will know about them but will not bloat the main UI (this is a main issue in the entire app at the moment, even without adding many new features).

I will reconsider if there's enough interest in something like this, but I'd say this feature is out of scope and not planned for the near future.

**Comment by KronosTheLate** [comment]
Completely fair. Thanks for your attention and thoughfullnes 😁

**Comment by Qronikarz** [comment]
I don't particularly care for the cards inheriting the color from the column, but it would be nice to set the color of the column manually. I don't know if I use Kanri correctly, but I use the columns as the state of the tasks so some visual distinction would be easier to tell at first glance which column is which.
